graph LR
    page_home(home)-->page_2(review_details)
    page_2-->page_home
    page_2-->page_about(about)
    modal
    page_home--navigation<br/>drawer-->page_about
    page_about--navigation<br/>drawer-->page_home